services:
  springboot-app:
    container_name: springboot-app
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysqldb
    ports:
    - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/CharityDonationDB
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root

  mysqldb:
    container_name: mysqldb
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CharityDonationDB
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  
  adminer:
     container_name: adminer
     image: adminer
     ports:
       - "8000:8080"